-- My Finance Records V13.0.0 · Cloud Schema V3
-- Profile-scoped encrypted record sync, household membership roles, immutable audit,
-- invitation codes, device revocation, and encrypted cloud restore points.
--
-- Run after the V12.21.0 Cloud Schema V2 migration. V2 tables are intentionally
-- preserved for rollback and are not modified by this migration.

begin;

create table if not exists public.finance_v3_profiles (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete restrict,
  name text not null check (char_length(name) between 1 and 80),
  profile_type text not null default 'personal' check (profile_type in ('personal','household')),
  encryption_salt text not null check (char_length(encryption_salt) between 8 and 200),
  encryption_check jsonb not null,
  kdf_iterations integer not null default 310000 check (kdf_iterations between 100000 and 2000000),
  cloud_schema_version integer not null default 3 check (cloud_schema_version = 3),
  min_app_version_code integer not null default 130000 check (min_app_version_code >= 130000),
  current_audit_id bigint not null default 0 check (current_audit_id >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.finance_v3_members (
  profile_id uuid not null references public.finance_v3_profiles(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','editor','viewer')),
  invited_by uuid references auth.users(id) on delete set null,
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (profile_id,user_id)
);

create unique index if not exists finance_v3_one_owner_idx
  on public.finance_v3_members(profile_id) where role='owner';

create table if not exists public.finance_v3_records (
  profile_id uuid not null references public.finance_v3_profiles(id) on delete cascade,
  collection text not null check (char_length(collection) between 1 and 60),
  record_id text not null check (char_length(record_id) between 1 and 240),
  payload jsonb not null check (payload ? '__financeEncrypted'),
  sort_index integer not null default 0,
  revision bigint not null default 1 check (revision > 0),
  deleted_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by_user uuid not null references auth.users(id) on delete restrict,
  updated_by_device text not null default '',
  app_version text not null default '',
  app_version_code integer not null default 130000,
  min_writer_version_code integer not null default 130000,
  finance_schema_version integer not null default 12,
  primary key (profile_id,collection,record_id)
);

create table if not exists public.finance_v3_batches (
  profile_id uuid not null references public.finance_v3_profiles(id) on delete cascade,
  batch_id text not null check (char_length(batch_id) between 1 and 180),
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  device_id text not null default '',
  status text not null default 'processing' check (status in ('processing','committed','conflict','rejected')),
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  committed_at timestamptz,
  primary key (profile_id,batch_id)
);

create table if not exists public.finance_v3_audit (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.finance_v3_profiles(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  batch_id text not null,
  collection text not null,
  record_id text not null,
  action text not null check (action in ('upsert','delete','restore')),
  revision bigint not null,
  payload jsonb not null,
  sort_index integer not null default 0,
  deleted_at timestamptz,
  device_id text not null default '',
  app_version text not null default '',
  app_version_code integer not null default 130000,
  created_at timestamptz not null default now(),
  constraint finance_v3_audit_once unique (profile_id,batch_id,collection,record_id)
);

create table if not exists public.finance_v3_devices (
  profile_id uuid not null references public.finance_v3_profiles(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text not null check (char_length(device_id) between 1 and 160),
  device_name text not null default 'Device',
  platform text not null default '',
  app_version text not null default '',
  app_version_code integer not null default 0,
  cloud_schema_version integer not null default 3,
  last_pull_audit_id bigint not null default 0,
  last_seen_at timestamptz not null default now(),
  last_sync_at timestamptz,
  last_push_at timestamptz,
  revoked_at timestamptz,
  revoked_by_user uuid references auth.users(id) on delete set null,
  revoked_by_device text not null default '',
  primary key (profile_id,user_id,device_id)
);

create table if not exists public.finance_v3_payment_operations (
  profile_id uuid not null references public.finance_v3_profiles(id) on delete cascade,
  operation_id text not null,
  expense_id text not null,
  operation_type text not null check (operation_type in ('expense_payment','gym_auto_payment','expense_payment_restore')),
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  account_name text not null default '',
  amount numeric(18,2) not null default 0 check (amount >= 0),
  device_id text not null default '',
  app_version text not null default '',
  created_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  primary key (profile_id,operation_id,expense_id,operation_type)
);

create table if not exists public.finance_v3_invites (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.finance_v3_profiles(id) on delete cascade,
  token_hash text not null unique check (char_length(token_hash)=64),
  role text not null check (role in ('editor','viewer')),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  accepted_at timestamptz,
  accepted_by uuid references auth.users(id) on delete set null,
  revoked_at timestamptz
);

create table if not exists public.finance_v3_restore_points (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.finance_v3_profiles(id) on delete cascade,
  label text not null check (char_length(label) between 1 and 120),
  encrypted_snapshot jsonb not null check (encrypted_snapshot ? '__financeEncrypted'),
  encryption_record_id text not null,
  summary jsonb not null default '{}'::jsonb,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists finance_v3_records_collection_idx on public.finance_v3_records(profile_id,collection,deleted_at,sort_index);
create index if not exists finance_v3_records_updated_idx on public.finance_v3_records(profile_id,updated_at desc);
create index if not exists finance_v3_audit_cursor_idx on public.finance_v3_audit(profile_id,id);
create index if not exists finance_v3_devices_active_idx on public.finance_v3_devices(profile_id,revoked_at,last_seen_at desc);
create index if not exists finance_v3_invites_profile_idx on public.finance_v3_invites(profile_id,expires_at desc);
create index if not exists finance_v3_restore_points_profile_idx on public.finance_v3_restore_points(profile_id,created_at desc);

create or replace function public.finance_v3_role(p_profile_id uuid)
returns text
language sql
stable
security definer
set search_path=''
as $$
  select m.role
  from public.finance_v3_members m
  where m.profile_id=p_profile_id and m.user_id=(select auth.uid())
$$;

create or replace function public.finance_v3_require_member(p_profile_id uuid, p_write boolean default false)
returns text
language plpgsql
stable
security definer
set search_path=''
as $$
declare v_role text;
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  select public.finance_v3_role(p_profile_id) into v_role;
  if v_role is null then raise exception 'profile_access_denied'; end if;
  if p_write and v_role not in ('owner','editor') then raise exception 'profile_read_only'; end if;
  return v_role;
end;
$$;

create or replace function public.finance_v3_list_profiles()
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_profiles jsonb;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'profile_id',p.id,'name',p.name,'profile_type',p.profile_type,'role',m.role,
    'encryption_salt',p.encryption_salt,'encryption_check',p.encryption_check,
    'kdf_iterations',p.kdf_iterations,'cloud_schema_version',p.cloud_schema_version,
    'min_app_version_code',p.min_app_version_code,'created_at',p.created_at,'updated_at',p.updated_at
  ) order by p.updated_at desc),'[]'::jsonb)
  into v_profiles
  from public.finance_v3_members m
  join public.finance_v3_profiles p on p.id=m.profile_id
  where m.user_id=v_uid;
  return jsonb_build_object('profiles',v_profiles);
end;
$$;

create or replace function public.finance_v3_create_profile(
  p_name text,
  p_profile_type text,
  p_encryption_salt text,
  p_encryption_check jsonb,
  p_kdf_iterations integer,
  p_min_app_version_code integer default 130000
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_profile public.finance_v3_profiles%rowtype;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;
  if coalesce(length(trim(p_name)),0)=0 then raise exception 'profile_name_required'; end if;
  if p_profile_type not in ('personal','household') then raise exception 'invalid_profile_type'; end if;
  if not coalesce(p_encryption_check ? '__financeEncrypted',false) then raise exception 'encrypted_key_check_required'; end if;
  insert into public.finance_v3_profiles(owner_user_id,name,profile_type,encryption_salt,encryption_check,kdf_iterations,min_app_version_code)
  values(v_uid,left(trim(p_name),80),p_profile_type,left(p_encryption_salt,200),p_encryption_check,greatest(100000,least(coalesce(p_kdf_iterations,310000),2000000)),greatest(coalesce(p_min_app_version_code,130000),130000))
  returning * into v_profile;
  insert into public.finance_v3_members(profile_id,user_id,role,invited_by) values(v_profile.id,v_uid,'owner',v_uid);
  return jsonb_build_object('profile_id',v_profile.id,'name',v_profile.name,'profile_type',v_profile.profile_type,'role','owner');
end;
$$;

create or replace function public.finance_v3_create_invite(p_profile_id uuid,p_token_hash text,p_role text,p_expires_hours integer default 72)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_id uuid; v_role text;
begin
  v_role:=public.finance_v3_require_member(p_profile_id,false);
  if v_role<>'owner' then raise exception 'owner_required'; end if;
  if p_role not in ('editor','viewer') then raise exception 'invalid_invite_role'; end if;
  if coalesce(length(p_token_hash),0)<>64 then raise exception 'invalid_invite_token'; end if;
  insert into public.finance_v3_invites(profile_id,token_hash,role,created_by,expires_at)
  values(p_profile_id,lower(p_token_hash),p_role,v_uid,now()+make_interval(hours=>greatest(1,least(coalesce(p_expires_hours,72),168))))
  returning id into v_id;
  return jsonb_build_object('invite_id',v_id,'role',p_role,'expires_at',(select expires_at from public.finance_v3_invites where id=v_id));
end;
$$;

create or replace function public.finance_v3_accept_invite(p_token_hash text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_invite public.finance_v3_invites%rowtype; v_profile public.finance_v3_profiles%rowtype;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;
  select * into v_invite from public.finance_v3_invites
   where token_hash=lower(p_token_hash) and accepted_at is null and revoked_at is null and expires_at>now()
   for update;
  if not found then raise exception 'invite_invalid_or_expired'; end if;
  insert into public.finance_v3_members(profile_id,user_id,role,invited_by)
  values(v_invite.profile_id,v_uid,v_invite.role,v_invite.created_by)
  on conflict(profile_id,user_id) do update set
    role=case when public.finance_v3_members.role='owner' then 'owner' else excluded.role end,
    invited_by=case when public.finance_v3_members.role='owner' then public.finance_v3_members.invited_by else excluded.invited_by end,
    updated_at=now();
  update public.finance_v3_invites set accepted_at=now(),accepted_by=v_uid where id=v_invite.id;
  select * into v_profile from public.finance_v3_profiles where id=v_invite.profile_id;
  return jsonb_build_object(
    'profile_id',v_profile.id,'name',v_profile.name,'profile_type',v_profile.profile_type,
    'role',(select role from public.finance_v3_members where profile_id=v_invite.profile_id and user_id=v_uid),
    'encryption_salt',v_profile.encryption_salt,'encryption_check',v_profile.encryption_check,'kdf_iterations',v_profile.kdf_iterations
  );
end;
$$;

create or replace function public.finance_v3_list_members(p_profile_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_role text; v_members jsonb;
begin
  v_role:=public.finance_v3_require_member(p_profile_id,false);
  select coalesce(jsonb_agg(jsonb_build_object('user_id',m.user_id,'email',u.email,'role',m.role,'joined_at',m.joined_at) order by case m.role when 'owner' then 1 when 'editor' then 2 else 3 end,u.email),'[]'::jsonb)
  into v_members
  from public.finance_v3_members m join auth.users u on u.id=m.user_id
  where m.profile_id=p_profile_id;
  return jsonb_build_object('members',v_members,'current_role',v_role);
end;
$$;

create or replace function public.finance_v3_set_member_role(p_profile_id uuid,p_member_user_id uuid,p_role text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_role text;
begin
  v_role:=public.finance_v3_require_member(p_profile_id,false);
  if v_role<>'owner' then raise exception 'owner_required'; end if;
  if p_role not in ('editor','viewer') then raise exception 'invalid_member_role'; end if;
  update public.finance_v3_members set role=p_role,updated_at=now()
  where profile_id=p_profile_id and user_id=p_member_user_id and role<>'owner';
  if not found then raise exception 'member_not_found_or_owner'; end if;
  return jsonb_build_object('status','updated','user_id',p_member_user_id,'role',p_role);
end;
$$;

create or replace function public.finance_v3_remove_member(p_profile_id uuid,p_member_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_role text;
begin
  v_role:=public.finance_v3_require_member(p_profile_id,false);
  if v_role<>'owner' then raise exception 'owner_required'; end if;
  delete from public.finance_v3_members where profile_id=p_profile_id and user_id=p_member_user_id and role<>'owner';
  if not found then raise exception 'member_not_found_or_owner'; end if;
  update public.finance_v3_devices set revoked_at=coalesce(revoked_at,now()),revoked_by_user=auth.uid()
   where profile_id=p_profile_id and user_id=p_member_user_id;
  return jsonb_build_object('status','removed','user_id',p_member_user_id);
end;
$$;

create or replace function public.finance_v3_register_device(
  p_profile_id uuid,p_device_id text,p_device_name text,p_platform text,p_app_version text,p_app_version_code integer,p_last_pull_audit_id bigint default 0
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_role text; v_device public.finance_v3_devices%rowtype;
begin
  v_role:=public.finance_v3_require_member(p_profile_id,false);
  if coalesce(length(trim(p_device_id)),0)=0 then raise exception 'device_id_required'; end if;
  select * into v_device from public.finance_v3_devices where profile_id=p_profile_id and user_id=v_uid and device_id=p_device_id;
  if found and v_device.revoked_at is not null then return jsonb_build_object('status','revoked','revoked_at',v_device.revoked_at); end if;
  insert into public.finance_v3_devices(profile_id,user_id,device_id,device_name,platform,app_version,app_version_code,cloud_schema_version,last_pull_audit_id,last_seen_at)
  values(p_profile_id,v_uid,left(trim(p_device_id),160),left(coalesce(nullif(trim(p_device_name),''),'Device'),80),left(coalesce(p_platform,''),300),left(coalesce(p_app_version,''),40),greatest(coalesce(p_app_version_code,0),0),3,greatest(coalesce(p_last_pull_audit_id,0),0),now())
  on conflict(profile_id,user_id,device_id) do update set device_name=excluded.device_name,platform=excluded.platform,app_version=excluded.app_version,app_version_code=excluded.app_version_code,cloud_schema_version=3,last_seen_at=now(),last_pull_audit_id=greatest(public.finance_v3_devices.last_pull_audit_id,excluded.last_pull_audit_id);
  return jsonb_build_object('status','active','device_id',p_device_id,'role',v_role);
end;
$$;

create or replace function public.finance_v3_revoke_device(p_profile_id uuid,p_user_id uuid,p_device_id text,p_revoked_by_device text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_role text;
begin
  v_role:=public.finance_v3_require_member(p_profile_id,false);
  if v_role<>'owner' and p_user_id<>v_uid then raise exception 'owner_or_self_required'; end if;
  update public.finance_v3_devices set revoked_at=coalesce(revoked_at,now()),revoked_by_user=v_uid,revoked_by_device=left(coalesce(p_revoked_by_device,''),160)
  where profile_id=p_profile_id and user_id=p_user_id and device_id=p_device_id;
  return jsonb_build_object('status',case when found then 'revoked' else 'not_found' end,'device_id',p_device_id);
end;
$$;

create or replace function public.finance_v3_snapshot(p_profile_id uuid,p_device_id text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_role text; v_profile public.finance_v3_profiles%rowtype; v_device public.finance_v3_devices%rowtype; v_records jsonb;
begin
  v_role:=public.finance_v3_require_member(p_profile_id,false);
  select * into v_device from public.finance_v3_devices where profile_id=p_profile_id and user_id=v_uid and device_id=p_device_id;
  if found and v_device.revoked_at is not null then return jsonb_build_object('status','revoked','revoked_at',v_device.revoked_at); end if;
  select * into v_profile from public.finance_v3_profiles where id=p_profile_id;
  select coalesce(jsonb_agg(jsonb_build_object(
    'collection',collection,'record_id',record_id,'payload',payload,'sort_index',sort_index,'revision',revision,
    'deleted_at',deleted_at,'updated_at',updated_at,'updated_by_user',updated_by_user,'updated_by_device',updated_by_device,
    'app_version',app_version,'app_version_code',app_version_code,'min_writer_version_code',min_writer_version_code
  ) order by collection,sort_index,record_id),'[]'::jsonb) into v_records
  from public.finance_v3_records where profile_id=p_profile_id;
  return jsonb_build_object('status','ok','profile_id',p_profile_id,'role',v_role,'records',v_records,'latest_audit_id',v_profile.current_audit_id,
    'cloud_schema_version',3,'min_app_version_code',v_profile.min_app_version_code,'encryption_salt',v_profile.encryption_salt,'encryption_check',v_profile.encryption_check,'kdf_iterations',v_profile.kdf_iterations);
end;
$$;

create or replace function public.finance_v3_pull(p_profile_id uuid,p_after_audit_id bigint,p_limit integer,p_device_id text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_role text; v_device public.finance_v3_devices%rowtype; v_events jsonb; v_latest bigint; v_limit integer:=greatest(1,least(coalesce(p_limit,250),500)); v_more boolean;
begin
  v_role:=public.finance_v3_require_member(p_profile_id,false);
  select * into v_device from public.finance_v3_devices where profile_id=p_profile_id and user_id=v_uid and device_id=p_device_id;
  if not found then return jsonb_build_object('status','device_missing'); end if;
  if v_device.revoked_at is not null then return jsonb_build_object('status','revoked','revoked_at',v_device.revoked_at); end if;
  with selected as (
    select * from public.finance_v3_audit where profile_id=p_profile_id and id>greatest(coalesce(p_after_audit_id,0),0) order by id limit v_limit+1
  ), page as (select * from selected order by id limit v_limit)
  select coalesce(jsonb_agg(jsonb_build_object('id',id,'collection',collection,'record_id',record_id,'payload',payload,'sort_index',sort_index,'revision',revision,'deleted_at',deleted_at,'updated_at',created_at,'updated_by_user',actor_user_id,'updated_by_device',device_id,'app_version',app_version,'app_version_code',app_version_code) order by id),'[]'::jsonb),
    coalesce(max(id),greatest(coalesce(p_after_audit_id,0),0)),(select count(*)>v_limit from selected)
  into v_events,v_latest,v_more from page;
  update public.finance_v3_devices set last_seen_at=now(),last_sync_at=now(),last_pull_audit_id=greatest(last_pull_audit_id,v_latest) where profile_id=p_profile_id and user_id=v_uid and device_id=p_device_id;
  return jsonb_build_object('status','ok','events',v_events,'latest_audit_id',v_latest,'has_more',coalesce(v_more,false),'role',v_role);
end;
$$;

create or replace function public.finance_v3_commit_batch(
  p_profile_id uuid,p_batch_id text,p_device_id text,p_app_version text,p_app_version_code integer,p_changes jsonb,p_migrated_from_v2 boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_uid uuid:=auth.uid(); v_role text; v_profile public.finance_v3_profiles%rowtype; v_existing public.finance_v3_records%rowtype;
  v_change jsonb; v_conflicts jsonb:='[]'::jsonb; v_results jsonb:='[]'::jsonb; v_result jsonb;
  v_collection text; v_record_id text; v_payload jsonb; v_expected bigint; v_sort integer; v_deleted boolean; v_revision bigint; v_deleted_at timestamptz; v_audit_id bigint; v_latest bigint:=0; v_min_writer integer;
begin
  v_role:=public.finance_v3_require_member(p_profile_id,true);
  if coalesce(length(trim(p_batch_id)),0)=0 then raise exception 'batch_id_required'; end if;
  if jsonb_typeof(p_changes)<>'array' then raise exception 'changes_must_be_array'; end if;
  if jsonb_array_length(p_changes)>500 then raise exception 'too_many_changes'; end if;
  select * into v_profile from public.finance_v3_profiles where id=p_profile_id for update;
  if p_app_version_code<v_profile.min_app_version_code then return jsonb_build_object('status','upgrade_required','min_app_version_code',v_profile.min_app_version_code); end if;
  if exists(select 1 from public.finance_v3_devices where profile_id=p_profile_id and user_id=v_uid and device_id=p_device_id and revoked_at is not null) then return jsonb_build_object('status','revoked'); end if;
  select result into v_result from public.finance_v3_batches where profile_id=p_profile_id and batch_id=p_batch_id;
  if found then return v_result; end if;
  insert into public.finance_v3_batches(profile_id,batch_id,actor_user_id,device_id) values(p_profile_id,left(p_batch_id,180),v_uid,left(p_device_id,160));

  for v_change in select value from jsonb_array_elements(p_changes) loop
    v_collection:=left(coalesce(v_change->>'collection',''),60); v_record_id:=left(coalesce(v_change->>'record_id',''),240);
    v_expected:=greatest(coalesce((v_change->>'base_revision')::bigint,0),0);
    v_min_writer:=greatest(coalesce((v_change->>'min_writer_version_code')::integer,p_app_version_code),130000);
    if v_collection='' or v_record_id='' then raise exception 'record_identity_required'; end if;
    if not coalesce((v_change->'payload') ? '__financeEncrypted',false) then raise exception 'encrypted_payload_required'; end if;
    select * into v_existing from public.finance_v3_records where profile_id=p_profile_id and collection=v_collection and record_id=v_record_id;
    if found and v_existing.min_writer_version_code>p_app_version_code then
      v_conflicts:=v_conflicts||jsonb_build_array(jsonb_build_object('collection',v_collection,'record_id',v_record_id,'reason','record_requires_newer_app','remote_revision',v_existing.revision,'remote_payload',v_existing.payload,'remote_deleted_at',v_existing.deleted_at));
    elsif found and v_existing.revision<>v_expected then
      v_conflicts:=v_conflicts||jsonb_build_array(jsonb_build_object('collection',v_collection,'record_id',v_record_id,'reason','revision_changed','expected_revision',v_expected,'remote_revision',v_existing.revision,'remote_payload',v_existing.payload,'remote_deleted_at',v_existing.deleted_at));
    elsif not found and v_expected<>0 then
      v_conflicts:=v_conflicts||jsonb_build_array(jsonb_build_object('collection',v_collection,'record_id',v_record_id,'reason','record_missing','expected_revision',v_expected,'remote_revision',0));
    end if;
  end loop;
  if jsonb_array_length(v_conflicts)>0 then
    v_result:=jsonb_build_object('status','conflict','conflicts',v_conflicts,'batch_id',p_batch_id);
    update public.finance_v3_batches set status='conflict',result=v_result,committed_at=now() where profile_id=p_profile_id and batch_id=p_batch_id;
    return v_result;
  end if;

  for v_change in select value from jsonb_array_elements(p_changes) loop
    v_collection:=left(v_change->>'collection',60); v_record_id:=left(v_change->>'record_id',240); v_payload:=v_change->'payload';
    v_sort:=coalesce((v_change->>'sort_index')::integer,0); v_deleted:=coalesce((v_change->>'deleted')::boolean,false); v_min_writer:=greatest(coalesce((v_change->>'min_writer_version_code')::integer,p_app_version_code),130000);
    select * into v_existing from public.finance_v3_records where profile_id=p_profile_id and collection=v_collection and record_id=v_record_id;
    v_revision:=case when found then v_existing.revision+1 else 1 end; v_deleted_at:=case when v_deleted then now() else null end;
    insert into public.finance_v3_records(profile_id,collection,record_id,payload,sort_index,revision,deleted_at,updated_at,updated_by_user,updated_by_device,app_version,app_version_code,min_writer_version_code,finance_schema_version)
    values(p_profile_id,v_collection,v_record_id,v_payload,v_sort,v_revision,v_deleted_at,now(),v_uid,left(p_device_id,160),left(coalesce(p_app_version,''),40),coalesce(p_app_version_code,0),v_min_writer,12)
    on conflict(profile_id,collection,record_id) do update set payload=excluded.payload,sort_index=excluded.sort_index,revision=excluded.revision,deleted_at=excluded.deleted_at,updated_at=excluded.updated_at,updated_by_user=excluded.updated_by_user,updated_by_device=excluded.updated_by_device,app_version=excluded.app_version,app_version_code=excluded.app_version_code,min_writer_version_code=greatest(public.finance_v3_records.min_writer_version_code,excluded.min_writer_version_code),finance_schema_version=12;
    insert into public.finance_v3_audit(profile_id,actor_user_id,batch_id,collection,record_id,action,revision,payload,sort_index,deleted_at,device_id,app_version,app_version_code)
    values(p_profile_id,v_uid,left(p_batch_id,180),v_collection,v_record_id,case when v_deleted then 'delete' else 'upsert' end,v_revision,v_payload,v_sort,v_deleted_at,left(p_device_id,160),left(coalesce(p_app_version,''),40),coalesce(p_app_version_code,0)) returning id into v_audit_id;
    v_latest:=greatest(v_latest,v_audit_id);
    v_results:=v_results||jsonb_build_array(jsonb_build_object('collection',v_collection,'record_id',v_record_id,'revision',v_revision,'payload',v_payload,'sort_index',v_sort,'deleted_at',v_deleted_at,'audit_id',v_audit_id,'app_version',p_app_version,'app_version_code',p_app_version_code));
  end loop;
  update public.finance_v3_profiles set current_audit_id=greatest(current_audit_id,v_latest),updated_at=now(),min_app_version_code=greatest(min_app_version_code,130000) where id=p_profile_id;
  update public.finance_v3_devices set last_seen_at=now(),last_sync_at=now(),last_push_at=now(),app_version=left(coalesce(p_app_version,''),40),app_version_code=coalesce(p_app_version_code,0),cloud_schema_version=3 where profile_id=p_profile_id and user_id=v_uid and device_id=p_device_id;
  v_result:=jsonb_build_object('status','committed','batch_id',p_batch_id,'records',v_results,'latest_audit_id',v_latest,'role',v_role,'migrated_from_v2',coalesce(p_migrated_from_v2,false));
  update public.finance_v3_batches set status='committed',result=v_result,committed_at=now() where profile_id=p_profile_id and batch_id=p_batch_id;
  return v_result;
end;
$$;

create or replace function public.finance_v3_commit_financial_operations(
  p_profile_id uuid,p_batch_id text,p_operations jsonb,p_device_id text,p_app_version text,p_app_version_code integer,p_changes jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_result jsonb; v_operation jsonb; v_type text;
begin
  perform public.finance_v3_require_member(p_profile_id,true);
  if jsonb_typeof(p_operations)<>'array' then raise exception 'operations_must_be_array'; end if;
  for v_operation in select value from jsonb_array_elements(p_operations) loop
    v_type:=coalesce(v_operation->>'operation_type','');
    if v_type not in ('expense_payment','gym_auto_payment','expense_payment_restore') then raise exception 'invalid_financial_operation'; end if;
  end loop;
  v_result:=public.finance_v3_commit_batch(p_profile_id,p_batch_id,p_device_id,p_app_version,p_app_version_code,p_changes,false);
  if v_result->>'status'='committed' then
    for v_operation in select value from jsonb_array_elements(p_operations) loop
      insert into public.finance_v3_payment_operations(profile_id,operation_id,expense_id,operation_type,actor_user_id,account_name,amount,device_id,app_version,payload)
      values(p_profile_id,left(v_operation->>'operation_id',180),left(v_operation->>'expense_id',180),v_operation->>'operation_type',v_uid,left(coalesce(v_operation->>'account_name',''),120),greatest(coalesce((v_operation->>'amount')::numeric,0),0),left(p_device_id,160),left(p_app_version,40),jsonb_build_object('cloud_schema_version',3,'batch_id',p_batch_id))
      on conflict(profile_id,operation_id,expense_id,operation_type) do nothing;
    end loop;
  end if;
  return v_result;
end;
$$;

create or replace function public.finance_v3_create_restore_point(p_profile_id uuid,p_label text,p_encrypted_snapshot jsonb,p_summary jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_id uuid; v_record_id text;
begin
  perform public.finance_v3_require_member(p_profile_id,true);
  if not coalesce(p_encrypted_snapshot ? '__financeEncrypted',false) then raise exception 'encrypted_snapshot_required'; end if;
  v_record_id:=coalesce(nullif(split_part(p_encrypted_snapshot->>'aad','|',4),''),'restore-point');
  insert into public.finance_v3_restore_points(profile_id,label,encrypted_snapshot,encryption_record_id,summary,created_by)
  values(p_profile_id,left(coalesce(nullif(trim(p_label),''),'Restore point'),120),p_encrypted_snapshot,left(v_record_id,300),coalesce(p_summary,'{}'::jsonb),v_uid)
  returning id into v_id;
  return jsonb_build_object('status','created','restore_point_id',v_id);
end;
$$;

create or replace function public.finance_v3_list_restore_points(p_profile_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_points jsonb;
begin
  perform public.finance_v3_require_member(p_profile_id,false);
  select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'label',r.label,'summary',r.summary,'created_at',r.created_at,'created_by',r.created_by,'created_by_email',u.email) order by r.created_at desc),'[]'::jsonb)
  into v_points from public.finance_v3_restore_points r join auth.users u on u.id=r.created_by where r.profile_id=p_profile_id;
  return jsonb_build_object('restore_points',v_points);
end;
$$;

create or replace function public.finance_v3_get_restore_point(p_profile_id uuid,p_restore_point_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_point public.finance_v3_restore_points%rowtype;
begin
  perform public.finance_v3_require_member(p_profile_id,false);
  select * into v_point from public.finance_v3_restore_points where profile_id=p_profile_id and id=p_restore_point_id;
  if not found then raise exception 'restore_point_not_found'; end if;
  return jsonb_build_object('id',v_point.id,'label',v_point.label,'encrypted_snapshot',v_point.encrypted_snapshot,'encryption_record_id',v_point.encryption_record_id,'summary',v_point.summary,'created_at',v_point.created_at);
end;
$$;

-- RLS: direct browser writes remain blocked. Mutations occur through security-definer RPCs.
do $$
declare t text;
begin
  foreach t in array array['finance_v3_profiles','finance_v3_members','finance_v3_records','finance_v3_batches','finance_v3_audit','finance_v3_devices','finance_v3_payment_operations','finance_v3_invites','finance_v3_restore_points'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('alter table public.%I force row level security',t);
    execute format('revoke all on public.%I from anon',t);
    execute format('revoke all on public.%I from authenticated',t);
  end loop;
end $$;

-- Read policies are profile-membership scoped. Sensitive invite tokens remain RPC-only.
grant select on public.finance_v3_profiles,public.finance_v3_members,public.finance_v3_records,public.finance_v3_batches,public.finance_v3_audit,public.finance_v3_devices,public.finance_v3_payment_operations,public.finance_v3_restore_points to authenticated;

drop policy if exists "finance v3 profiles member read" on public.finance_v3_profiles;
create policy "finance v3 profiles member read" on public.finance_v3_profiles for select to authenticated using (public.finance_v3_role(id) is not null);
drop policy if exists "finance v3 members member read" on public.finance_v3_members;
create policy "finance v3 members member read" on public.finance_v3_members for select to authenticated using (public.finance_v3_role(profile_id) is not null);
drop policy if exists "finance v3 records member read" on public.finance_v3_records;
create policy "finance v3 records member read" on public.finance_v3_records for select to authenticated using (public.finance_v3_role(profile_id) is not null);
drop policy if exists "finance v3 batches member read" on public.finance_v3_batches;
create policy "finance v3 batches member read" on public.finance_v3_batches for select to authenticated using (public.finance_v3_role(profile_id) is not null);
drop policy if exists "finance v3 audit member read" on public.finance_v3_audit;
create policy "finance v3 audit member read" on public.finance_v3_audit for select to authenticated using (public.finance_v3_role(profile_id) is not null);
drop policy if exists "finance v3 devices member read" on public.finance_v3_devices;
create policy "finance v3 devices member read" on public.finance_v3_devices for select to authenticated using (public.finance_v3_role(profile_id) is not null);
drop policy if exists "finance v3 payments member read" on public.finance_v3_payment_operations;
create policy "finance v3 payments member read" on public.finance_v3_payment_operations for select to authenticated using (public.finance_v3_role(profile_id) is not null);
drop policy if exists "finance v3 restore member read" on public.finance_v3_restore_points;
create policy "finance v3 restore member read" on public.finance_v3_restore_points for select to authenticated using (public.finance_v3_role(profile_id) is not null);

-- The membership helper is used by RLS policies, so authenticated users need EXECUTE.
-- It reveals only the caller's own role (or null) for the supplied profile ID.
revoke execute on function public.finance_v3_role(uuid) from public,anon;
grant execute on function public.finance_v3_role(uuid) to authenticated;
revoke execute on function public.finance_v3_require_member(uuid,boolean) from public,anon,authenticated;

-- RPC execution grants.
do $$
declare r record;
begin
  for r in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'finance_v3_%' and p.proname not in ('finance_v3_role','finance_v3_require_member') loop
    execute format('revoke execute on function %s from public,anon',r.signature);
    execute format('grant execute on function %s to authenticated',r.signature);
  end loop;
end $$;

comment on table public.finance_v3_records is 'Cloud Schema V3 profile-scoped encrypted record rows. The server stores ciphertext envelopes and cannot read finance payload fields.';
comment on table public.finance_v3_audit is 'Immutable profile-scoped record audit history containing encrypted payload envelopes.';
comment on table public.finance_v3_restore_points is 'Encrypted client-created profile snapshots. The encryption passphrase is never stored by the database.';

-- Realtime notifications contain metadata and encrypted payload envelopes only.
do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='finance_v3_audit') then alter publication supabase_realtime add table public.finance_v3_audit; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='finance_v3_devices') then alter publication supabase_realtime add table public.finance_v3_devices; end if;
end $$;

commit;
