-- My Finance Records V12.21.0 · Cloud Schema V2
-- Record-level synchronization, immutable audit history, device revocation,
-- optimistic revisions, and atomic multi-record commits.
-- Run once in the Supabase SQL Editor after the V12.19.1 security migration.

begin;

create table if not exists public.finance_sync_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  cloud_schema_version integer not null default 2 check (cloud_schema_version >= 2),
  current_audit_id bigint not null default 0 check (current_audit_id >= 0),
  min_app_version_code integer not null default 120210 check (min_app_version_code > 0),
  migrated_from_v1 boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.finance_sync_records (
  user_id uuid not null references auth.users(id) on delete cascade,
  collection text not null check (char_length(collection) between 1 and 60),
  record_id text not null check (char_length(record_id) between 1 and 240),
  payload jsonb not null default '{}'::jsonb,
  sort_index integer not null default 0,
  revision bigint not null default 1 check (revision > 0),
  deleted_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by_device text not null default '',
  app_version text not null default '',
  app_version_code integer not null default 120210,
  min_writer_version_code integer not null default 120210,
  schema_version integer not null default 12,
  primary key (user_id, collection, record_id)
);

create table if not exists public.finance_sync_batches (
  user_id uuid not null references auth.users(id) on delete cascade,
  batch_id text not null check (char_length(batch_id) between 1 and 180),
  device_id text not null default '',
  status text not null default 'processing' check (status in ('processing','committed','conflict','rejected')),
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  committed_at timestamptz,
  primary key (user_id, batch_id)
);

create table if not exists public.finance_sync_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  batch_id text not null,
  collection text not null,
  record_id text not null,
  action text not null check (action in ('upsert','delete')),
  revision bigint not null,
  payload jsonb not null default '{}'::jsonb,
  sort_index integer not null default 0,
  deleted_at timestamptz,
  device_id text not null default '',
  app_version text not null default '',
  app_version_code integer not null default 120210,
  created_at timestamptz not null default now(),
  constraint finance_sync_audit_once unique (user_id, batch_id, collection, record_id)
);

alter table public.finance_cloud_devices
  add column if not exists app_version_code integer not null default 0,
  add column if not exists cloud_schema_version integer not null default 1,
  add column if not exists last_pull_audit_id bigint not null default 0,
  add column if not exists last_push_at timestamptz,
  add column if not exists revoked_at timestamptz,
  add column if not exists revoked_by_device text not null default '';

create index if not exists finance_sync_records_updated_idx
  on public.finance_sync_records(user_id, updated_at desc);
create index if not exists finance_sync_records_collection_idx
  on public.finance_sync_records(user_id, collection, deleted_at, sort_index);
create index if not exists finance_sync_audit_user_cursor_idx
  on public.finance_sync_audit(user_id, id);
create index if not exists finance_sync_batches_created_idx
  on public.finance_sync_batches(user_id, created_at desc);
create index if not exists finance_cloud_devices_active_idx
  on public.finance_cloud_devices(user_id, revoked_at, last_seen_at desc);

create or replace function public.finance_jsonb_deep_merge(original jsonb, incoming jsonb)
returns jsonb
language sql
immutable
parallel safe
as $$
  select case
    when jsonb_typeof(coalesce(original, '{}'::jsonb)) = 'object'
     and jsonb_typeof(coalesce(incoming, '{}'::jsonb)) = 'object'
    then coalesce((
      select jsonb_object_agg(key, value)
      from (
        select key,
          case
            when original ? key and incoming ? key
              then public.finance_jsonb_deep_merge(original -> key, incoming -> key)
            when incoming ? key then incoming -> key
            else original -> key
          end as value
        from (
          select jsonb_object_keys(coalesce(original, '{}'::jsonb)) as key
          union
          select jsonb_object_keys(coalesce(incoming, '{}'::jsonb)) as key
        ) keys
      ) merged
    ), '{}'::jsonb)
    else coalesce(incoming, original, 'null'::jsonb)
  end;
$$;

create or replace function public.finance_sync_register_device(
  p_device_id text,
  p_device_name text,
  p_platform text,
  p_app_version text,
  p_app_version_code integer,
  p_last_pull_audit_id bigint default 0
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_existing public.finance_cloud_devices%rowtype;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;
  if coalesce(length(trim(p_device_id)), 0) = 0 then raise exception 'device_id_required'; end if;

  select * into v_existing
  from public.finance_cloud_devices
  where user_id = v_uid and device_id = p_device_id;

  if found and v_existing.revoked_at is not null then
    return jsonb_build_object(
      'status','revoked',
      'revoked_at',v_existing.revoked_at,
      'device_id',p_device_id
    );
  end if;

  insert into public.finance_cloud_devices (
    user_id, device_id, device_name, platform, app_version, app_version_code,
    cloud_schema_version, last_seen_at, last_pull_audit_id
  ) values (
    v_uid, left(trim(p_device_id), 160), left(coalesce(nullif(trim(p_device_name),''),'Device'), 80),
    left(coalesce(p_platform,''), 300), left(coalesce(p_app_version,''), 40),
    greatest(coalesce(p_app_version_code,0),0), 2, now(), greatest(coalesce(p_last_pull_audit_id,0),0)
  )
  on conflict (user_id, device_id) do update set
    device_name = excluded.device_name,
    platform = excluded.platform,
    app_version = excluded.app_version,
    app_version_code = excluded.app_version_code,
    cloud_schema_version = 2,
    last_seen_at = now(),
    last_pull_audit_id = greatest(public.finance_cloud_devices.last_pull_audit_id, excluded.last_pull_audit_id);

  return jsonb_build_object('status','active','device_id',p_device_id);
end;
$$;

create or replace function public.finance_sync_revoke_device(
  p_device_id text,
  p_revoked_by_device text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_count integer;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;
  update public.finance_cloud_devices
     set revoked_at = coalesce(revoked_at, now()),
         revoked_by_device = left(coalesce(p_revoked_by_device,''),160)
   where user_id = v_uid and device_id = p_device_id;
  get diagnostics v_count = row_count;
  return jsonb_build_object('status',case when v_count > 0 then 'revoked' else 'not_found' end,'device_id',p_device_id);
end;
$$;

create or replace function public.finance_sync_snapshot(p_device_id text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_device public.finance_cloud_devices%rowtype;
  v_profile public.finance_sync_profiles%rowtype;
  v_records jsonb;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;
  select * into v_device from public.finance_cloud_devices where user_id=v_uid and device_id=p_device_id;
  if found and v_device.revoked_at is not null then
    return jsonb_build_object('status','revoked','revoked_at',v_device.revoked_at);
  end if;

  select * into v_profile from public.finance_sync_profiles where user_id=v_uid;
  select coalesce(jsonb_agg(jsonb_build_object(
      'collection',collection,
      'record_id',record_id,
      'payload',payload,
      'sort_index',sort_index,
      'revision',revision,
      'deleted_at',deleted_at,
      'updated_at',updated_at,
      'updated_by_device',updated_by_device,
      'app_version',app_version,
      'app_version_code',app_version_code,
      'min_writer_version_code',min_writer_version_code
    ) order by collection,sort_index,record_id), '[]'::jsonb)
    into v_records
    from public.finance_sync_records
   where user_id=v_uid;

  return jsonb_build_object(
    'status','ok',
    'records',v_records,
    'latest_audit_id',coalesce(v_profile.current_audit_id,0),
    'cloud_schema_version',coalesce(v_profile.cloud_schema_version,2),
    'min_app_version_code',coalesce(v_profile.min_app_version_code,120210),
    'migrated_from_v1',coalesce(v_profile.migrated_from_v1,false)
  );
end;
$$;

create or replace function public.finance_sync_pull(
  p_after_audit_id bigint,
  p_limit integer,
  p_device_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_device public.finance_cloud_devices%rowtype;
  v_events jsonb;
  v_latest bigint := greatest(coalesce(p_after_audit_id,0),0);
  v_limit integer := greatest(1,least(coalesce(p_limit,250),500));
  v_has_more boolean := false;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;
  select * into v_device from public.finance_cloud_devices where user_id=v_uid and device_id=p_device_id;
  if not found then return jsonb_build_object('status','device_missing'); end if;
  if v_device.revoked_at is not null then return jsonb_build_object('status','revoked','revoked_at',v_device.revoked_at); end if;

  with selected as (
    select * from public.finance_sync_audit
     where user_id=v_uid and id > greatest(coalesce(p_after_audit_id,0),0)
     order by id asc
     limit v_limit + 1
  ), page as (
    select * from selected order by id asc limit v_limit
  )
  select coalesce(jsonb_agg(jsonb_build_object(
      'id',id,
      'batch_id',batch_id,
      'collection',collection,
      'record_id',record_id,
      'action',action,
      'revision',revision,
      'payload',payload,
      'sort_index',sort_index,
      'deleted_at',deleted_at,
      'device_id',device_id,
      'app_version',app_version,
      'app_version_code',app_version_code,
      'created_at',created_at
    ) order by id), '[]'::jsonb),
    coalesce(max(id),greatest(coalesce(p_after_audit_id,0),0))
    into v_events,v_latest
    from page;

  select exists(
    select 1 from public.finance_sync_audit
     where user_id=v_uid and id > v_latest
  ) into v_has_more;

  update public.finance_cloud_devices
     set last_seen_at=now(), last_pull_audit_id=greatest(last_pull_audit_id,v_latest)
   where user_id=v_uid and device_id=p_device_id;

  return jsonb_build_object('status','ok','events',v_events,'latest_audit_id',v_latest,'has_more',v_has_more);
end;
$$;

create or replace function public.finance_sync_commit_batch(
  p_batch_id text,
  p_device_id text,
  p_app_version text,
  p_app_version_code integer,
  p_changes jsonb,
  p_migrated_from_v1 boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_device public.finance_cloud_devices%rowtype;
  v_profile public.finance_sync_profiles%rowtype;
  v_existing_batch public.finance_sync_batches%rowtype;
  v_claimed integer := 0;
  v_change jsonb;
  v_existing public.finance_sync_records%rowtype;
  v_collection text;
  v_record_id text;
  v_expected bigint;
  v_deleted boolean;
  v_payload jsonb;
  v_sort_index integer;
  v_min_writer integer;
  v_new_revision bigint;
  v_merged jsonb;
  v_deleted_at timestamptz;
  v_audit_id bigint;
  v_latest_audit bigint := 0;
  v_conflicts jsonb := '[]'::jsonb;
  v_results jsonb := '[]'::jsonb;
  v_result jsonb;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;
  if jsonb_typeof(p_changes) <> 'array' then raise exception 'changes_must_be_array'; end if;
  if jsonb_array_length(p_changes) > 500 then raise exception 'too_many_changes'; end if;
  if coalesce(length(trim(p_batch_id)),0)=0 then raise exception 'batch_id_required'; end if;

  select * into v_device from public.finance_cloud_devices where user_id=v_uid and device_id=p_device_id for update;
  if not found then return jsonb_build_object('status','device_missing'); end if;
  if v_device.revoked_at is not null then return jsonb_build_object('status','revoked','revoked_at',v_device.revoked_at); end if;

  insert into public.finance_sync_batches(user_id,batch_id,device_id,status,result)
    values(v_uid,left(p_batch_id,180),left(p_device_id,160),'processing',jsonb_build_object('status','processing','batch_id',p_batch_id))
    on conflict(user_id,batch_id) do nothing;
  get diagnostics v_claimed = row_count;
  if v_claimed = 0 then
    select * into v_existing_batch from public.finance_sync_batches where user_id=v_uid and batch_id=p_batch_id;
    return coalesce(v_existing_batch.result,jsonb_build_object('status','processing','batch_id',p_batch_id));
  end if;

  insert into public.finance_sync_profiles(user_id,cloud_schema_version,min_app_version_code,migrated_from_v1)
  values(v_uid,2,120210,coalesce(p_migrated_from_v1,false))
  on conflict(user_id) do update set
    cloud_schema_version=2,
    migrated_from_v1=public.finance_sync_profiles.migrated_from_v1 or excluded.migrated_from_v1,
    updated_at=now();

  select * into v_profile from public.finance_sync_profiles where user_id=v_uid for update;
  if coalesce(p_app_version_code,0) < v_profile.min_app_version_code then
    v_result := jsonb_build_object('status','upgrade_required','min_app_version_code',v_profile.min_app_version_code);
    update public.finance_sync_batches
       set status='rejected',result=v_result,committed_at=now()
     where user_id=v_uid and batch_id=p_batch_id;
    return v_result;
  end if;

  for v_change in select value from jsonb_array_elements(p_changes)
  loop
    v_collection := left(coalesce(v_change->>'collection',''),60);
    v_record_id := left(coalesce(v_change->>'record_id',''),240);
    v_expected := greatest(coalesce((v_change->>'base_revision')::bigint,0),0);
    v_min_writer := greatest(coalesce((v_change->>'min_writer_version_code')::integer,p_app_version_code),120210);
    if v_collection = '' or v_record_id = '' then raise exception 'invalid_record_key'; end if;

    select * into v_existing
      from public.finance_sync_records
     where user_id=v_uid and collection=v_collection and record_id=v_record_id
     for update;

    if found then
      if v_existing.revision <> v_expected then
        v_conflicts := v_conflicts || jsonb_build_array(jsonb_build_object(
          'collection',v_collection,'record_id',v_record_id,'reason','revision_conflict',
          'expected_revision',v_expected,'remote_revision',v_existing.revision,
          'remote_payload',v_existing.payload,'remote_sort_index',v_existing.sort_index,
          'remote_deleted_at',v_existing.deleted_at,
          'remote_app_version',v_existing.app_version,
          'remote_app_version_code',v_existing.app_version_code
        ));
      elsif coalesce(p_app_version_code,0) < v_existing.min_writer_version_code then
        v_conflicts := v_conflicts || jsonb_build_array(jsonb_build_object(
          'collection',v_collection,'record_id',v_record_id,'reason','record_requires_newer_app',
          'expected_revision',v_expected,'remote_revision',v_existing.revision,
          'remote_payload',v_existing.payload,'remote_sort_index',v_existing.sort_index,
          'remote_deleted_at',v_existing.deleted_at,
          'min_writer_version_code',v_existing.min_writer_version_code
        ));
      end if;
    elsif v_expected <> 0 then
      v_conflicts := v_conflicts || jsonb_build_array(jsonb_build_object(
        'collection',v_collection,'record_id',v_record_id,'reason','record_missing',
        'expected_revision',v_expected,'remote_revision',0
      ));
    end if;
  end loop;

  if jsonb_array_length(v_conflicts) > 0 then
    v_result := jsonb_build_object('status','conflict','conflicts',v_conflicts,'batch_id',p_batch_id);
    update public.finance_sync_batches
       set status='conflict',result=v_result,committed_at=now()
     where user_id=v_uid and batch_id=p_batch_id;
    return v_result;
  end if;

  for v_change in select value from jsonb_array_elements(p_changes)
  loop
    v_collection := left(v_change->>'collection',60);
    v_record_id := left(v_change->>'record_id',240);
    v_deleted := coalesce((v_change->>'deleted')::boolean,false);
    v_payload := coalesce(v_change->'payload','{}'::jsonb);
    v_sort_index := coalesce((v_change->>'sort_index')::integer,0);
    v_min_writer := greatest(coalesce((v_change->>'min_writer_version_code')::integer,p_app_version_code),120210);

    select * into v_existing
      from public.finance_sync_records
     where user_id=v_uid and collection=v_collection and record_id=v_record_id;

    v_new_revision := case when found then v_existing.revision + 1 else 1 end;
    v_deleted_at := case when v_deleted then now() else null end;
    v_merged := case
      when v_deleted then coalesce(v_existing.payload,v_payload,'{}'::jsonb)
      when found then public.finance_jsonb_deep_merge(v_existing.payload,v_payload)
      else v_payload
    end;

    insert into public.finance_sync_records(
      user_id,collection,record_id,payload,sort_index,revision,deleted_at,updated_at,
      updated_by_device,app_version,app_version_code,min_writer_version_code,schema_version
    ) values (
      v_uid,v_collection,v_record_id,v_merged,v_sort_index,v_new_revision,v_deleted_at,now(),
      left(p_device_id,160),left(coalesce(p_app_version,''),40),coalesce(p_app_version_code,0),v_min_writer,12
    )
    on conflict(user_id,collection,record_id) do update set
      payload=excluded.payload,
      sort_index=excluded.sort_index,
      revision=excluded.revision,
      deleted_at=excluded.deleted_at,
      updated_at=excluded.updated_at,
      updated_by_device=excluded.updated_by_device,
      app_version=excluded.app_version,
      app_version_code=excluded.app_version_code,
      min_writer_version_code=greatest(public.finance_sync_records.min_writer_version_code,excluded.min_writer_version_code),
      schema_version=excluded.schema_version;

    insert into public.finance_sync_audit(
      user_id,batch_id,collection,record_id,action,revision,payload,sort_index,deleted_at,
      device_id,app_version,app_version_code
    ) values (
      v_uid,left(p_batch_id,180),v_collection,v_record_id,case when v_deleted then 'delete' else 'upsert' end,
      v_new_revision,v_merged,v_sort_index,v_deleted_at,left(p_device_id,160),left(coalesce(p_app_version,''),40),coalesce(p_app_version_code,0)
    ) returning id into v_audit_id;

    v_latest_audit := greatest(v_latest_audit,v_audit_id);
    v_results := v_results || jsonb_build_array(jsonb_build_object(
      'collection',v_collection,'record_id',v_record_id,'revision',v_new_revision,
      'payload',v_merged,'sort_index',v_sort_index,'deleted_at',v_deleted_at,
      'audit_id',v_audit_id,'app_version',p_app_version,'app_version_code',p_app_version_code
    ));
  end loop;

  update public.finance_sync_profiles
     set current_audit_id=greatest(current_audit_id,v_latest_audit),updated_at=now()
   where user_id=v_uid;
  update public.finance_cloud_devices
     set last_seen_at=now(),last_sync_at=now(),last_push_at=now(),app_version=left(coalesce(p_app_version,''),40),
         app_version_code=coalesce(p_app_version_code,0),cloud_schema_version=2
   where user_id=v_uid and device_id=p_device_id;

  v_result := jsonb_build_object('status','committed','batch_id',p_batch_id,'records',v_results,'latest_audit_id',v_latest_audit);
  update public.finance_sync_batches
     set status='committed',result=v_result,committed_at=now()
   where user_id=v_uid and batch_id=p_batch_id;
  return v_result;
end;
$$;

create or replace function public.finance_sync_commit_financial_operations(
  p_batch_id text,
  p_operations jsonb,
  p_device_id text,
  p_app_version text,
  p_app_version_code integer,
  p_changes jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_result jsonb;
  v_operation jsonb;
  v_type text;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;
  if jsonb_typeof(p_operations) <> 'array' then raise exception 'operations_must_be_array'; end if;
  if jsonb_array_length(p_operations) > 500 then raise exception 'too_many_operations'; end if;

  for v_operation in select value from jsonb_array_elements(p_operations)
  loop
    v_type := coalesce(v_operation->>'operation_type','');
    if v_type not in ('expense_payment','gym_auto_payment','expense_payment_restore') then
      raise exception 'invalid_financial_operation';
    end if;
    if coalesce(length(trim(v_operation->>'operation_id')),0)=0
       or coalesce(length(trim(v_operation->>'expense_id')),0)=0 then
      raise exception 'financial_operation_identity_required';
    end if;
  end loop;

  v_result := public.finance_sync_commit_batch(
    p_batch_id,p_device_id,p_app_version,p_app_version_code,p_changes,false
  );

  if v_result->>'status' = 'committed' then
    for v_operation in select value from jsonb_array_elements(p_operations)
    loop
      insert into public.finance_payment_operations(
        user_id,operation_id,expense_id,operation_type,account_name,amount,occurred_at,device_id,app_version,payload
      ) values (
        v_uid,left(coalesce(v_operation->>'operation_id',''),180),left(coalesce(v_operation->>'expense_id',''),180),
        v_operation->>'operation_type',left(coalesce(v_operation->>'account_name',''),120),
        greatest(coalesce((v_operation->>'amount')::numeric,0),0),now(),left(coalesce(p_device_id,''),160),
        left(coalesce(p_app_version,''),40),jsonb_build_object('cloud_schema_version',2,'batch_id',v_result->>'batch_id')
      ) on conflict(user_id,operation_id,expense_id,operation_type) do nothing;
    end loop;
  end if;
  return v_result;
end;
$$;

create or replace function public.finance_sync_commit_financial_operation(
  p_operation_id text,
  p_operation_type text,
  p_expense_id text,
  p_account_name text,
  p_amount numeric,
  p_device_id text,
  p_app_version text,
  p_app_version_code integer,
  p_changes jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_result jsonb;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;
  if p_operation_type not in ('expense_payment','gym_auto_payment','expense_payment_restore') then
    raise exception 'invalid_financial_operation';
  end if;

  return public.finance_sync_commit_financial_operations(
    'financial:' || left(coalesce(p_operation_id,''),110) || ':' || pg_catalog.md5(coalesce(p_changes,'[]'::jsonb)::text),
    jsonb_build_array(jsonb_build_object(
      'operation_id',p_operation_id,'operation_type',p_operation_type,'expense_id',p_expense_id,
      'account_name',p_account_name,'amount',p_amount
    )),
    p_device_id,p_app_version,p_app_version_code,p_changes
  );
end;
$$;

alter table public.finance_sync_profiles enable row level security;
alter table public.finance_sync_records enable row level security;
alter table public.finance_sync_batches enable row level security;
alter table public.finance_sync_audit enable row level security;
alter table public.finance_sync_profiles force row level security;
alter table public.finance_sync_records force row level security;
alter table public.finance_sync_batches force row level security;
alter table public.finance_sync_audit force row level security;

revoke all on public.finance_sync_profiles from anon;
revoke all on public.finance_sync_records from anon;
revoke all on public.finance_sync_batches from anon;
revoke all on public.finance_sync_audit from anon;
revoke all on public.finance_sync_profiles from authenticated;
revoke all on public.finance_sync_records from authenticated;
revoke all on public.finance_sync_batches from authenticated;
revoke all on public.finance_sync_audit from authenticated;
grant select on public.finance_sync_profiles to authenticated;
grant select on public.finance_sync_records to authenticated;
grant select on public.finance_sync_batches to authenticated;
grant select on public.finance_sync_audit to authenticated;

revoke insert,update,delete on public.finance_cloud_devices from authenticated;
grant select on public.finance_cloud_devices to authenticated;

drop policy if exists "finance sync profiles select own" on public.finance_sync_profiles;
drop policy if exists "finance sync records select own" on public.finance_sync_records;
drop policy if exists "finance sync batches select own" on public.finance_sync_batches;
drop policy if exists "finance sync audit select own" on public.finance_sync_audit;
create policy "finance sync profiles select own" on public.finance_sync_profiles
for select to authenticated using ((select auth.uid()) is not null and (select auth.uid())=user_id);
create policy "finance sync records select own" on public.finance_sync_records
for select to authenticated using ((select auth.uid()) is not null and (select auth.uid())=user_id);
create policy "finance sync batches select own" on public.finance_sync_batches
for select to authenticated using ((select auth.uid()) is not null and (select auth.uid())=user_id);
create policy "finance sync audit select own" on public.finance_sync_audit
for select to authenticated using ((select auth.uid()) is not null and (select auth.uid())=user_id);

revoke execute on function public.finance_jsonb_deep_merge(jsonb,jsonb) from public,anon,authenticated;
revoke execute on function public.finance_sync_register_device(text,text,text,text,integer,bigint) from public,anon;
revoke execute on function public.finance_sync_revoke_device(text,text) from public,anon;
revoke execute on function public.finance_sync_snapshot(text) from public,anon;
revoke execute on function public.finance_sync_pull(bigint,integer,text) from public,anon;
revoke execute on function public.finance_sync_commit_batch(text,text,text,integer,jsonb,boolean) from public,anon;
revoke execute on function public.finance_sync_commit_financial_operations(text,jsonb,text,text,integer,jsonb) from public,anon;
revoke execute on function public.finance_sync_commit_financial_operation(text,text,text,text,numeric,text,text,integer,jsonb) from public,anon;
grant execute on function public.finance_sync_register_device(text,text,text,text,integer,bigint) to authenticated;
grant execute on function public.finance_sync_revoke_device(text,text) to authenticated;
grant execute on function public.finance_sync_snapshot(text) to authenticated;
grant execute on function public.finance_sync_pull(bigint,integer,text) to authenticated;
grant execute on function public.finance_sync_commit_batch(text,text,text,integer,jsonb,boolean) to authenticated;
grant execute on function public.finance_sync_commit_financial_operations(text,jsonb,text,text,integer,jsonb) to authenticated;
grant execute on function public.finance_sync_commit_financial_operation(text,text,text,text,numeric,text,text,integer,jsonb) to authenticated;

comment on table public.finance_sync_records is 'Cloud Schema V2 current record rows. Writes occur only through atomic RPC functions.';
comment on table public.finance_sync_audit is 'Immutable record-level synchronization audit log.';
comment on function public.finance_sync_commit_batch is 'Atomically validates and commits one or more changed records using optimistic revisions.';

-- Realtime notifications use immutable audit inserts rather than full-state updates.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
     where pubname='supabase_realtime' and schemaname='public' and tablename='finance_sync_audit'
  ) then
    alter publication supabase_realtime add table public.finance_sync_audit;
  end if;
  if not exists (
    select 1 from pg_publication_tables
     where pubname='supabase_realtime' and schemaname='public' and tablename='finance_cloud_devices'
  ) then
    alter publication supabase_realtime add table public.finance_cloud_devices;
  end if;
end $$;

commit;
