-- My Finance Records V12.19.0 · Cloud Schema V1
-- Run in the Supabase SQL Editor before enabling Cloud Sync.

create table if not exists public.finance_cloud_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  revision bigint not null default 1 check (revision > 0),
  updated_at timestamptz not null default now(),
  updated_by_device text not null default '',
  app_version text not null default '',
  schema_version integer not null default 12
);

create table if not exists public.finance_cloud_devices (
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text not null,
  device_name text not null default 'Device',
  platform text not null default '',
  app_version text not null default '',
  last_seen_at timestamptz not null default now(),
  last_sync_at timestamptz,
  primary key (user_id, device_id)
);

create table if not exists public.finance_payment_operations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  operation_id text not null,
  expense_id text not null,
  operation_type text not null check (operation_type in ('expense_payment','gym_auto_payment','expense_payment_restore')),
  account_name text not null default '',
  amount numeric(18,2) not null default 0 check (amount >= 0),
  occurred_at timestamptz not null default now(),
  device_id text not null default '',
  app_version text not null default '',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint finance_payment_operations_once unique (user_id, operation_id, expense_id, operation_type)
);

create index if not exists finance_cloud_state_updated_idx on public.finance_cloud_state(updated_at desc);
create index if not exists finance_cloud_devices_seen_idx on public.finance_cloud_devices(user_id, last_seen_at desc);
create index if not exists finance_payment_operations_expense_idx on public.finance_payment_operations(user_id, expense_id, occurred_at desc);

create or replace function public.finance_cloud_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists finance_cloud_state_touch on public.finance_cloud_state;
create trigger finance_cloud_state_touch
before update on public.finance_cloud_state
for each row execute function public.finance_cloud_touch_updated_at();

-- Realtime is optional but recommended. The block is safe to run more than once.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'finance_cloud_state'
  ) then
    alter publication supabase_realtime add table public.finance_cloud_state;
  end if;
end $$;
