#!/usr/bin/env node
import assert from "node:assert/strict";
import fs from "node:fs";
const read = file => fs.readFileSync(file, "utf8");
const pkg = JSON.parse(read("package.json"));
const lock = JSON.parse(read("package-lock.json"));
const version = JSON.parse(read("version.json"));
const index = read("index.html");
const uiCss = read("ui-icon-alignment-v15-0-5.css");
const palette = read("black-canvas-v15-1-0.css");
const worker = read("sw.js");
const updater = read("pwa-update-v15-0-5.js");
const cloud = read("cloud-sync.js");
const runtime = read("sync-config.js");
const readme = read("README.md");
const changelog = read("CHANGELOG.md");
const installer = read("Install_V15_1_0.command");
assert.equal(pkg.version,"15.1.0");
assert.equal(lock.version,"15.1.0");
assert.equal(lock.packages?.[""]?.version,"15.1.0");
assert.equal(version.version,"15.1.0");
assert.equal(version.schemaVersion,12);
assert.equal(version.cloudSchemaVersion,3);
assert.equal(version.name,"Black Canvas UI");
assert.equal(version.cacheVersion,"finance-v15-20260815-black-canvas-r15");
assert.match(index,/<title>My Finance Records · V15\.1\.0<\/title>/);
assert.match(index,/const APP_VERSION = "15\.1\.0";/);
assert.match(index,/const APP_RELEASE_NAME = "Black Canvas UI";/);
assert.match(index,/ui-icon-alignment-v15-0-5\.css\?v=15\.1\.0-ui2/);
assert.match(index,/pwa-update-v15-0-5\.js\?v=15\.1\.0/);
assert.ok(index.indexOf('dashboard-interactions.css?v=14.0.23') < index.indexOf('ui-icon-alignment-v15-0-5.css?v=15.1.0-ui2'));
assert.match(uiCss,/html body #buildBadge::before/);
assert.match(uiCss,/content:none !important/);
assert.match(uiCss,/gap:4px !important/);
assert.match(palette,/--bg:#000000/);
assert.match(palette,/--primary:#173e76/);
assert.match(updater,/FINANCE_CACHE_PATTERN/);
assert.match(worker,/const APP_VERSION = "15\.1\.0";/);
assert.match(worker,/finance-v15-20260815-black-canvas-r15/);
assert.match(cloud,/const APP_VERSION_FALLBACK = "15\.1\.0";/);
assert.match(runtime,/const VERSION = "15\.1\.0";/);
assert.match(runtime,/const RELEASE_NAME = "Black Canvas UI";/);
assert.ok(readme.startsWith("# My Finance Records · V15.1.0"));
assert.ok(changelog.startsWith("## 15.1.0 · 2026-08-15"));
assert.match(installer,/V15\.1\.0/);
console.log("V15.1.0 release validation passed.");
