#!/usr/bin/env node
import assert from "node:assert/strict";
import fs from "node:fs";
const read = file => fs.readFileSync(file, "utf8");
const pkg = JSON.parse(read("package.json"));
const lock = JSON.parse(read("package-lock.json"));
const version = JSON.parse(read("version.json"));
const index = read("index.html");
const worker = read("sw.js");
const cloud = read("cloud-sync.js");
const runtime = read("sync-config.js");
const readme = read("README.md");
const changelog = read("CHANGELOG.md");
const installer = read("Install_V15_0_4.command");
assert.equal(pkg.version,"15.0.4");
assert.equal(lock.version,"15.0.4");
assert.equal(lock.packages?.[""]?.version,"15.0.4");
assert.equal(version.version,"15.0.4");
assert.equal(version.schemaVersion,12);
assert.equal(version.cloudSchemaVersion,3);
assert.equal(version.name,"Record Spending Reliability");
assert.equal(version.cacheVersion,"finance-v15-20260815-record-spending-r8");
assert.match(index,/<title>My Finance Records · V15\.0\.4<\/title>/);
assert.match(index,/const APP_VERSION = "15\.0\.4";/);
assert.match(index,/const APP_RELEASE_NAME = "Record Spending Reliability";/);
assert.match(index,/"version":"V15\.0\.4","title":"Record Spending Reliability"/);
assert.match(worker,/const APP_VERSION = "15\.0\.4";/);
assert.match(cloud,/const APP_VERSION_FALLBACK = "15\.0\.4";/);
assert.match(runtime,/const VERSION = "15\.0\.4";/);
assert.match(runtime,/const RELEASE_NAME = "Record Spending Reliability";/);
assert.ok(readme.startsWith("# My Finance Records · V15.0.4"));
assert.ok(changelog.startsWith("## 15.0.4 · 2026-08-15"));
assert.match(installer,/V15\.0\.4/);
console.log("V15.0.4 release validation passed.");
