#!/usr/bin/env node
import assert from "node:assert/strict";
import fs from "node:fs";
const read = file => fs.readFileSync(file, "utf8");
const pkg = JSON.parse(read("package.json"));
const lock = JSON.parse(read("package-lock.json"));
const version = JSON.parse(read("version.json"));
const index = read("index.html");
const uiCss = read("ui-icon-alignment-v15-0-4.css");
const worker = read("sw.js");
const cloud = read("cloud-sync.js");
const runtime = read("sync-config.js");
const readme = read("README.md");
const changelog = read("CHANGELOG.md");
const installer = read("Install_V15_0_4.command");
assert.equal(pkg.version,"15.0.4");
assert.equal(lock.version,"15.0.4");
assert.equal(lock.packages?.[""]?.version,"15.0.4");
assert.equal(version.version,"15.0.4");
assert.equal(version.schemaVersion,12);
assert.equal(version.cloudSchemaVersion,3);
assert.equal(version.name,"Record Spending Reliability");
assert.equal(version.cacheVersion,"finance-v15-20260815-ui-align-r12");
assert.match(index,/<title>My Finance Records · V15\.0\.4<\/title>/);
assert.match(index,/const APP_VERSION = "15\.0\.4";/);
assert.match(index,/const APP_RELEASE_NAME = "Record Spending Reliability";/);
assert.match(index,/"version":"V15\.0\.4","title":"Record Spending Reliability"/);
assert.match(index,/ui-icon-alignment-v15-0-4\.css\?v=15\.0\.4-ui3/);
assert.ok(index.indexOf('dashboard-interactions.css?v=15.2.10-icons1') < index.indexOf('ui-icon-alignment-v15-0-4.css?v=15.0.4-ui3'), "production UI alignment stylesheet must load after dashboard interactions");
assert.doesNotMatch(index,/ui-icon-alignment-v15-0-4\.css\?v=15\.0\.4-ui1/);
assert.match(worker,/ui-icon-alignment-v15-0-4\.css\?v=15\.0\.4-ui3/);
assert.match(worker,/finance-v15-20260815-ui-align-r12/);
assert.match(worker,/new Request\(url, \{ cache:"reload" \}\)/);
assert.match(uiCss,/V15\.0\.4 · cascade-safe icon alignment hotfix/);
assert.match(uiCss,/html body #buildBadge::before/);
assert.match(uiCss,/content:none !important/);
assert.match(uiCss,/html body #addAccountButton/);
assert.match(uiCss,/gap:4px !important/);
assert.match(uiCss,/html body #customizeDashboardButton\[data-dashboard-toolbar-action\]/);
assert.match(uiCss,/place-items:center !important/);
assert.match(worker,/const APP_VERSION = "15\.0\.4";/);
assert.match(cloud,/const APP_VERSION_FALLBACK = "15\.0\.4";/);
assert.match(runtime,/const VERSION = "15\.0\.4";/);
assert.match(runtime,/const RELEASE_NAME = "Record Spending Reliability";/);
assert.ok(readme.startsWith("# My Finance Records · V15.0.4"));
assert.ok(changelog.startsWith("## 15.0.4 · 2026-08-15"));
assert.match(installer,/V15\.0\.4/);
console.log("V15.0.4 release validation passed.");
